"use client";

import { Product } from "./Columns";
import {
  MdInventory,
  MdBuild,
  MdPhoneIphone,
  MdLaptop,
  MdKitchen,
  MdHome,
} from "react-icons/md";

export const products: Product[] = [
  {
    id: "prod1",
    name: "Smartphone X",
    supplier: "TechTrend Innovations",
    sku: 1001,
    status: "published",
    category: "electronics",
    quantityInStock: 50,
    price: 699.99,
    icon: MdPhoneIphone,
  },
  {
    id: "prod2",
    name: "Cotton T-Shirt",
    supplier: "FashionHub",
    sku: 2002,
    status: "published",
    category: "clothing",
    quantityInStock: 200,
    price: 19.99,
    icon: MdInventory,
  },
  {
    id: "prod3",
    name: "Sci-Fi Novel",
    supplier: "BookWorld",
    sku: 3003,
    status: "draft",
    category: "books",
    quantityInStock: 30,
    price: 12.5,
    icon: MdInventory,
  },
  {
    id: "prod4",
    name: "Desk Lamp",
    supplier: "HomeEssentials",
    sku: 4004,
    status: "published",
    category: "home",
    quantityInStock: 75,
    price: 29.99,
    icon: MdHome,
  },
  {
    id: "prod5",
    name: "Building Blocks Set",
    supplier: "ToyGalaxy",
    sku: 5005,
    status: "inactive",
    category: "toys",
    quantityInStock: 10,
    price: 49.99,
    icon: MdBuild,
  },
  {
    id: "prod6",
    name: "Tennis Racket",
    supplier: "SportZone",
    sku: 6006,
    status: "published",
    category: "sports",
    quantityInStock: 25,
    price: 89.99,
    icon: MdInventory,
  },
  {
    id: "prod7",
    name: "Moisturizing Cream",
    supplier: "BeautyBliss",
    sku: 7007,
    status: "published",
    category: "beauty",
    quantityInStock: 100,
    price: 24.99,
    icon: MdInventory,
  },
  {
    id: "prod8",
    name: "Car Floor Mats",
    supplier: "AutoGear",
    sku: 8008,
    status: "draft",
    category: "automotive",
    quantityInStock: 40,
    price: 39.99,
    icon: MdBuild,
  },
  {
    id: "prod9",
    name: "Laptop Pro",
    supplier: "TechTrend Innovations",
    sku: 1009,
    status: "published",
    category: "electronics",
    quantityInStock: 20,
    price: 1299.99,
    icon: MdLaptop,
  },
  {
    id: "prod10",
    name: "Kitchen Mixer",
    supplier: "HomeEssentials",
    sku: 4010,
    status: "inactive",
    category: "home",
    quantityInStock: 15,
    price: 199.99,
    icon: MdKitchen,
  },
];
