import {
  MdInventory,
  MdBuild,
  MdPhoneIphone,
  MdLaptop,
  MdKitchen,
  MdHome,
  MdHeadset,
  MdSpeaker,
  MdTablet,
  MdVideogameAsset,
  MdWatch,
  MdSportsTennis,
  MdFace,
  MdCarRental,
  MdToys,
  MdBook,
  MdLightbulb,
} from "react-icons/md";
import { Product } from "./Columns";

export const products: Product[] = [
  // Existing 10 products
  {
    id: "prod1",
    name: "Smartphone X",
    supplier: "TechTrend Innovations",
    sku: 1001,
    status: "published",
    category: "electronics",
    quantityInStock: 50,
    price: 699.99,
    icon: MdPhoneIphone,
  },
  {
    id: "prod2",
    name: "Cotton T-Shirt",
    supplier: "FashionHub",
    sku: 2002,
    status: "published",
    category: "clothing",
    quantityInStock: 200,
    price: 19.99,
    icon: MdInventory,
  },
  {
    id: "prod3",
    name: "Sci-Fi Novel",
    supplier: "BookWorld",
    sku: 3003,
    status: "draft",
    category: "books",
    quantityInStock: 30,
    price: 12.5,
    icon: MdInventory,
  },
  {
    id: "prod4",
    name: "Desk Lamp",
    supplier: "HomeEssentials",
    sku: 4004,
    status: "published",
    category: "home",
    quantityInStock: 75,
    price: 29.99,
    icon: MdHome,
  },
  {
    id: "prod5",
    name: "Building Blocks Set",
    supplier: "ToyGalaxy",
    sku: 5005,
    status: "inactive",
    category: "toys",
    quantityInStock: 10,
    price: 49.99,
    icon: MdBuild,
  },
  {
    id: "prod6",
    name: "Tennis Racket",
    supplier: "SportZone",
    sku: 6006,
    status: "published",
    category: "sports",
    quantityInStock: 25,
    price: 89.99,
    icon: MdInventory,
  },
  {
    id: "prod7",
    name: "Moisturizing Cream",
    supplier: "BeautyBliss",
    sku: 7007,
    status: "published",
    category: "beauty",
    quantityInStock: 100,
    price: 24.99,
    icon: MdInventory,
  },
  {
    id: "prod8",
    name: "Car Floor Mats",
    supplier: "AutoGear",
    sku: 8008,
    status: "draft",
    category: "automotive",
    quantityInStock: 40,
    price: 39.99,
    icon: MdBuild,
  },
  {
    id: "prod9",
    name: "Laptop Pro",
    supplier: "TechTrend Innovations",
    sku: 1009,
    status: "published",
    category: "electronics",
    quantityInStock: 20,
    price: 1299.99,
    icon: MdLaptop,
  },
  {
    id: "prod10",
    name: "Kitchen Mixer",
    supplier: "HomeEssentials",
    sku: 4010,
    status: "inactive",
    category: "home",
    quantityInStock: 15,
    price: 199.99,
    icon: MdKitchen,
  },
  // 30 new products
  {
    id: "prod11",
    name: "Wireless Earbuds",
    supplier: "TechTrend Innovations",
    sku: 1011,
    status: "published",
    category: "electronics",
    quantityInStock: 80,
    price: 149.99,
    icon: MdHeadset,
  },
  {
    id: "prod12",
    name: "Denim Jeans",
    supplier: "FashionHub",
    sku: 2012,
    status: "published",
    category: "clothing",
    quantityInStock: 150,
    price: 49.99,
    icon: MdInventory,
  },
  {
    id: "prod13",
    name: "Mystery Novel",
    supplier: "BookWorld",
    sku: 3013,
    status: "draft",
    category: "books",
    quantityInStock: 25,
    price: 15.99,
    icon: MdBook,
  },
  {
    id: "prod14",
    name: "Throw Blanket",
    supplier: "HomeEssentials",
    sku: 4014,
    status: "published",
    category: "home",
    quantityInStock: 60,
    price: 34.99,
    icon: MdHome,
  },
  {
    id: "prod15",
    name: "Action Figure Set",
    supplier: "ToyGalaxy",
    sku: 5015,
    status: "inactive",
    category: "toys",
    quantityInStock: 12,
    price: 29.99,
    icon: MdToys,
  },
  {
    id: "prod16",
    name: "Soccer Ball",
    supplier: "SportZone",
    sku: 6016,
    status: "published",
    category: "sports",
    quantityInStock: 30,
    price: 24.99,
    icon: MdSportsTennis,
  },
  {
    id: "prod17",
    name: "Face Serum",
    supplier: "BeautyBliss",
    sku: 7017,
    status: "published",
    category: "beauty",
    quantityInStock: 90,
    price: 39.99,
    icon: MdFace,
  },
  {
    id: "prod18",
    name: "Car Air Freshener",
    supplier: "AutoGear",
    sku: 8018,
    status: "draft",
    category: "automotive",
    quantityInStock: 50,
    price: 9.99,
    icon: MdCarRental,
  },
  {
    id: "prod19",
    name: "Gaming Console",
    supplier: "TechTrend Innovations",
    sku: 1019,
    status: "published",
    category: "electronics",
    quantityInStock: 15,
    price: 499.99,
    icon: MdVideogameAsset,
  },
  {
    id: "prod20",
    name: "Coffee Maker",
    supplier: "HomeEssentials",
    sku: 4020,
    status: "inactive",
    category: "home",
    quantityInStock: 10,
    price: 89.99,
    icon: MdKitchen,
  },
  {
    id: "prod21",
    name: "Smart Watch",
    supplier: "TechTrend Innovations",
    sku: 1021,
    status: "published",
    category: "electronics",
    quantityInStock: 40,
    price: 249.99,
    icon: MdWatch,
  },
  {
    id: "prod22",
    name: "Wool Scarf",
    supplier: "FashionHub",
    sku: 2022,
    status: "published",
    category: "clothing",
    quantityInStock: 100,
    price: 29.99,
    icon: MdInventory,
  },
  {
    id: "prod23",
    name: "History Book",
    supplier: "BookWorld",
    sku: 3023,
    status: "draft",
    category: "books",
    quantityInStock: 20,
    price: 19.99,
    icon: MdBook,
  },
  {
    id: "prod24",
    name: "Table Runner",
    supplier: "HomeEssentials",
    sku: 4024,
    status: "published",
    category: "home",
    quantityInStock: 45,
    price: 14.99,
    icon: MdHome,
  },
  {
    id: "prod25",
    name: "Puzzle Game",
    supplier: "ToyGalaxy",
    sku: 5025,
    status: "inactive",
    category: "toys",
    quantityInStock: 8,
    price: 19.99,
    icon: MdToys,
  },
  {
    id: "prod26",
    name: "Yoga Mat",
    supplier: "SportZone",
    sku: 6026,
    status: "published",
    category: "sports",
    quantityInStock: 35,
    price: 39.99,
    icon: MdSportsTennis,
  },
  {
    id: "prod27",
    name: "Lip Balm",
    supplier: "BeautyBliss",
    sku: 7027,
    status: "published",
    category: "beauty",
    quantityInStock: 120,
    price: 4.99,
    icon: MdFace,
  },
  {
    id: "prod28",
    name: "Car Wax",
    supplier: "AutoGear",
    sku: 8028,
    status: "draft",
    category: "automotive",
    quantityInStock: 25,
    price: 19.99,
    icon: MdCarRental,
  },
  {
    id: "prod29",
    name: "Bluetooth Speaker",
    supplier: "TechTrend Innovations",
    sku: 1029,
    status: "published",
    category: "electronics",
    quantityInStock: 60,
    price: 79.99,
    icon: MdSpeaker,
  },
  {
    id: "prod30",
    name: "Toaster Oven",
    supplier: "HomeEssentials",
    sku: 4030,
    status: "inactive",
    category: "home",
    quantityInStock: 12,
    price: 69.99,
    icon: MdKitchen,
  },
  {
    id: "prod31",
    name: "Leather Jacket",
    supplier: "FashionHub",
    sku: 2031,
    status: "published",
    category: "clothing",
    quantityInStock: 50,
    price: 99.99,
    icon: MdInventory,
  },
  {
    id: "prod32",
    name: "Cookbook",
    supplier: "BookWorld",
    sku: 3032,
    status: "draft",
    category: "books",
    quantityInStock: 15,
    price: 24.99,
    icon: MdBook,
  },
  {
    id: "prod33",
    name: "Wall Clock",
    supplier: "HomeEssentials",
    sku: 4033,
    status: "published",
    category: "home",
    quantityInStock: 30,
    price: 44.99,
    icon: MdHome,
  },
  {
    id: "prod34",
    name: "Remote Control Car",
    supplier: "ToyGalaxy",
    sku: 5034,
    status: "inactive",
    category: "toys",
    quantityInStock: 20,
    price: 59.99,
    icon: MdToys,
  },
  {
    id: "prod35",
    name: "Dumbbell Set",
    supplier: "SportZone",
    sku: 6035,
    status: "published",
    category: "sports",
    quantityInStock: 10,
    price: 149.99,
    icon: MdSportsTennis,
  },
  {
    id: "prod36",
    name: "Shampoo",
    supplier: "BeautyBliss",
    sku: 7036,
    status: "published",
    category: "beauty",
    quantityInStock: 80,
    price: 14.99,
    icon: MdFace,
  },
  {
    id: "prod37",
    name: "Tire Inflator",
    supplier: "AutoGear",
    sku: 8037,
    status: "draft",
    category: "automotive",
    quantityInStock: 35,
    price: 49.99,
    icon: MdCarRental,
  },
  {
    id: "prod38",
    name: "Tablet",
    supplier: "TechTrend Innovations",
    sku: 1038,
    status: "published",
    category: "electronics",
    quantityInStock: 25,
    price: 399.99,
    icon: MdTablet,
  },
  {
    id: "prod39",
    name: "Cutlery Set",
    supplier: "HomeEssentials",
    sku: 4039,
    status: "inactive",
    category: "home",
    quantityInStock: 18,
    price: 79.99,
    icon: MdKitchen,
  },
  {
    id: "prod40",
    name: "Running Shoes",
    supplier: "SportZone",
    sku: 6040,
    status: "published",
    category: "sports",
    quantityInStock: 40,
    price: 119.99,
    icon: MdSportsTennis,
  },
];
